language: node_js
node_js:
- '0.12'
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install -g bower grunt-cli
- gem install sass
- bower install
services: mongodb
script:
- USE_SAUCELABS=0 grunt test
notifications:
  slack:
    secure: M8Fw+bn6NJBgYiedYbspjwoo84pGyC0T4POhQLXUZrel3Qm9GhPGbxyoIxJpRkvfGG0gAvmqLk0ZJ3punFShWJwMutni4tat8Ok6GbORZ1xC/VuVrYM8yUDLit6oz3c8YiZltQBMmf9dH8HYd4ml4prKp3ifPLQmy593wRG9zHETfZad/KI7xEwTRklhvAePr/9VdTX9z5687DS9yJWxGevonXZOcwUNTU01CR3Gy7l2A5+m5uw73ZxNc46+Uf6l5lZvoe4Ez24HQScybsednDM+nhnukbynI5EEGLN/d2qy5tCnh3ydsIyaC3lzXYUXvHImmiaIedphebLTbquIB78LtOEMAWsXJtNV2WElQHB47joNOMMfC8oeI3KqoRSoF1qlsrV4KHa6ltb4m1t32Tm/G5xVAPJnfIJjjbq+b+RRA+/i9XSIAbmQRbl65WloKPD84ncN9NLTvyEiXwoIq9x81IAq3OYjvo30gpaE5xUDgO3B/7bGB2/sAETEVpxxWrSD5POzWOrkrUGQzQ27dXKquvHHtlhSnxQm8kFqfs9qnAVpziFIWATh7x1sNqOt2bvcRkZ4tzI0pUDldpdKCpebqlCOPb/k078yx1ZcnqCq7g3gvsYGPnDTBYAzNBCz+bJjhsqv3II8W8Q2oxT09c1JD8pwImNKt2SQAQhKLHc=
